### ISSUE TITLE
Unable to Launch Pack via MultiMC - InvocationTargetException

### ISSUE THREAD

**Issue by knaveightt** [AK9Official/All-of-Fabric#43]
Hello,

While following the installation instructions for running the pack with MultiMC, I received the following error:

```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Mod resolution took too long!
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:596)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:157)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
```

I am attaching the full log file as I am unsure how the error was thrown. I can provide additional information as requested. 
[latest.log](https://github.com/AllOfFabric/AOF-Normal/files/3628460/latest.log)

**Comment by Yoosk** [comment]
I would suggest to update java and check again.

**Comment by knaveightt** [comment]
Hello,

Upon re-installation of the pack via MultiMC, i was able to successfully launch. I believe it was an issue on my side, with the original installation not running successfully.

All good on my side, closing the issue :)
